### ISSUE TITLE
MIME type not set with S3 upload

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/aruna#147]
Maybe related to https://github.com/ArunaStorage/DataProxy/issues/30.

If I upload files via S3, no MIME type is set. Even if I explicitly upload/modify the type:

```
$ s3cmd put -m 'image/jpeg' -r so242_1_83_subset2 s3://biigletest/
$ s3cmd modify -m 'image/jpeg' s3://biigletest/so242_1_83_subset2/20150814_080600_IMG_37001.JPG
```

it is not set:

```
$ s3cmd info s3://biigletest/so242_1_83_subset2/20150814_080600_IMG_37001.JPG
s3://biigletest/so242_1_83_subset2/20150814_080600_IMG_37001.JPG (object):
   File size: 641698
   Last mod:  Tue, 27 Feb 2024 09:47:53 GMT
   MIME type: none
   Storage:   STANDARD
   MD5 sum:   01HQMZ6W995TF1S6VGFC5YG96D
   SSE:       none
   Policy:    none
   CORS:      <?xml version="1.0" encoding="UTF-8"?><CORSConfiguration><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>GET</AllowedMethod><AllowedOrigin>https://biigle.de</AllowedOrigin><MaxAgeSeconds>30</MaxAgeSeconds></CORSRule></CORSConfiguration>
   ACL:       none
```

I noticed this because BIIGLE checks the MIME type before it creates an image collection. This must have worked before (as I have created collections successfully in the past). Maybe I'm doing something wrong?

**Comment by St4NNi** [comment]
Sorry for the long, wait this was merged a long time ago. Please go ahead and test it and just let us know if it still does not work.

**Comment by mzur** [comment]
I finally managed to test this in your dev instance (I wrote an email about my issues with the production instance). The MIME type is correct now :+1:
